/*
 * Authored campaign data.
 *
 * This file intentionally has no imports or exports: it can be loaded with a
 * plain <script> tag before the game code.  The runtime may use as many of
 * these fields as it supports and safely fall back to its procedural defaults
 * for older builds.
 */
export const CAMPAIGN = [
  { title: 'Le jardin du terrier', theme: 'meadow', tutorial: 'Explore le jardin, ouvre 3 caisses et ramasse les carottes !', trapCount: 2, cubeCount: 3, coinCount: 3, bossHp: 45, bossFireInterval: 2500, bossDamage: 10, mechanic: 'apprentissage', layout: { traps: [{x:2,y:6},{x:6,y:3}], cubes: [{x:1,y:7,value:5},{x:7,y:6,value:5},{x:2,y:2,dead:false,value:8}], coins: [{x:3,y:7,value:2},{x:5,y:5,value:2},{x:6,y:2,value:3}], pickups: [{x:3,y:4,type:'shield'}] } },
  { title: 'Premiers pas', theme: 'meadow', tutorial: 'Les cases rouges annoncent un piège : observe avant d’avancer.', trapCount: 3, cubeCount: 4, coinCount: 4, bossHp: 50, bossFireInterval: 2400, bossDamage: 10, mechanic: 'pièges visibles', layout: { traps: [{x:2,y:7},{x:6,y:6},{x:2,y:3}], cubes: [{x:1,y:8,value:5},{x:7,y:7,value:5},{x:1,y:3,dead:true,value:4},{x:7,y:2,value:8}], coins: [{x:3,y:8,value:2},{x:5,y:7,value:2},{x:3,y:4,value:3},{x:6,y:2,value:3}] } },
  { title: 'La haie mystérieuse', theme: 'meadow', tutorial: 'Chaque caisse cache une surprise. Reste toujours en mouvement !', trapCount: 3, cubeCount: 5, coinCount: 4, bossHp: 55, bossFireInterval: 2300, bossDamage: 11, mechanic: 'caisses surprises', layout: { traps: [{x:1,y:6},{x:7,y:5},{x:1,y:2}], cubes: [{x:2,y:8,value:5},{x:6,y:7,value:5},{x:2,y:5,dead:false,value:6},{x:6,y:3,dead:true,value:3},{x:2,y:1,value:9}], coins: [{x:3,y:7,value:2},{x:5,y:6,value:2},{x:3,y:3,value:3},{x:6,y:1,value:3}], pickups: [{x:3,y:5,type:'carrot'}] } },
  { title: 'Pluie de printemps', theme: 'meadow', trapCount: 4, cubeCount: 5, coinCount: 5, bossHp: 60, bossFireInterval: 2200, bossDamage: 11, mechanic: 'esquive et cadence', layout: { traps: [{x:1,y:7},{x:7,y:7},{x:1,y:3},{x:7,y:2}], cubes: [{x:2,y:8,value:5},{x:6,y:8,value:5},{x:2,y:6,dead:true,value:3},{x:6,y:4,value:7},{x:2,y:1,value:10}], coins: [{x:3,y:8,value:2},{x:5,y:7,value:2},{x:3,y:5,value:3},{x:5,y:3,value:3},{x:3,y:1,value:4}], pickups: [{x:5,y:5,type:'shield'}] } },
  { title: 'Le pont de bois', theme: 'forest', tutorial: 'Le chemin se complique : planifie deux déplacements à l’avance.', trapCount: 4, cubeCount: 6, coinCount: 5, bossHp: 65, bossFireInterval: 2150, bossDamage: 12, mechanic: 'pont étroit' },
  { title: 'Clairière des lucioles', theme: 'forest', trapCount: 5, cubeCount: 6, coinCount: 6, bossHp: 70, bossFireInterval: 2050, bossDamage: 12, pattern: 'cross', mechanic: 'lucioles guides' },
  { title: 'Le vieux chêne', theme: 'forest', tutorial: 'Le boss vise ta position. Une esquive au bon moment fait la différence.', trapCount: 5, cubeCount: 7, coinCount: 6, bossHp: 78, bossFireInterval: 2000, bossDamage: 13, mechanic: 'boss viseur' },
  { title: 'Sentier des glands', theme: 'forest', trapCount: 6, cubeCount: 7, coinCount: 7, bossHp: 85, bossFireInterval: 1900, bossDamage: 13, pattern: 'cross', mechanic: 'racines mouvantes', layout: { traps: [{x:1,y:8},{x:7,y:8},{x:1,y:6},{x:7,y:5},{x:2,y:2},{x:6,y:1}], cubes: [{x:2,y:8,value:6},{x:6,y:7,value:6},{x:2,y:6,dead:true,value:4},{x:6,y:5,value:8},{x:2,y:3,value:8},{x:6,y:2,dead:false,value:6},{x:2,y:1,value:12}], coins: [{x:3,y:8,value:2},{x:5,y:7,value:2},{x:3,y:6,value:3},{x:5,y:4,value:3},{x:3,y:3,value:3},{x:5,y:2,value:4},{x:3,y:1,value:5}], pickups: [{x:3,y:5,type:'carrot'}] } },
  { title: 'La grotte bleue', theme: 'cave', tutorial: 'Dans la grotte, les pièges sont nombreux. Les caisses restent ton meilleur allié.', trapCount: 6, cubeCount: 7, coinCount: 7, bossHp: 92, bossFireInterval: 1850, bossDamage: 14, mechanic: 'parois bleues' },
  { title: 'Cristaux rebondissants', theme: 'cave', trapCount: 7, cubeCount: 8, coinCount: 8, bossHp: 100, bossFireInterval: 1800, bossDamage: 14, doubleShot: true, mechanic: 'tirs rebondissants' },
  { title: 'Le lac souterrain', theme: 'cave', tutorial: 'Deux projectiles peuvent arriver ensemble : garde une case de côté libre.', trapCount: 7, cubeCount: 8, coinCount: 8, bossHp: 108, bossFireInterval: 1750, bossDamage: 15, doubleShot: true, mechanic: 'deux salves' },
  { title: 'Galerie des échos', theme: 'cave', trapCount: 8, cubeCount: 8, coinCount: 9, bossHp: 116, bossFireInterval: 1700, bossDamage: 15, doubleShot: true, pattern: 'cross', mechanic: 'cristaux rebondissants', layout: { traps: [{x:1,y:8},{x:7,y:8},{x:1,y:6},{x:7,y:6},{x:2,y:4},{x:6,y:4},{x:1,y:2},{x:7,y:2}], cubes: [{x:2,y:8,value:6},{x:6,y:8,value:6},{x:2,y:6,dead:true,value:4},{x:6,y:6,value:8},{x:0,y:4,value:8},{x:5,y:4,dead:false,value:6},{x:2,y:2,value:10},{x:6,y:1,value:12}], coins: [{x:3,y:8,value:2},{x:5,y:7,value:2},{x:3,y:6,value:3},{x:5,y:5,value:3},{x:3,y:4,value:3},{x:5,y:3,value:4},{x:3,y:2,value:4},{x:5,y:1,value:5},{x:2,y:1,value:5}], pickups: [{x:3,y:5,type:'shield'}] } },
  { title: 'Le désert doré', theme: 'desert', tutorial: 'La chaleur accélère le danger. Attrape les pièces et termine vite !', trapCount: 7, cubeCount: 8, coinCount: 9, bossHp: 124, bossFireInterval: 1650, bossDamage: 16, special: 'haste', mechanic: 'chaleur accélérée' },
  { title: 'Dunes dansantes', theme: 'desert', trapCount: 8, cubeCount: 9, coinCount: 9, bossHp: 132, bossFireInterval: 1600, bossDamage: 16, doubleShot: true, special: 'haste', mechanic: 'dunes mouvantes' },
  { title: 'Le temple du soleil', theme: 'desert', tutorial: 'Les salves sont rapides maintenant : utilise le tir large si tu l’as débloqué.', trapCount: 8, cubeCount: 9, coinCount: 10, bossHp: 140, bossFireInterval: 1550, bossDamage: 17, doubleShot: true, special: 'haste', mechanic: 'rayons du soleil' },
  { title: 'Chambre des scarabées', theme: 'desert', trapCount: 9, cubeCount: 9, coinCount: 10, bossHp: 150, bossFireInterval: 1500, bossDamage: 17, doubleShot: true, pattern: 'cross', special: 'haste', mechanic: 'sable rapide', layout: { traps: [{x:1,y:8},{x:7,y:8},{x:1,y:7},{x:7,y:6},{x:1,y:5},{x:6,y:4},{x:1,y:3},{x:7,y:2},{x:2,y:1}], cubes: [{x:2,y:8,value:7},{x:6,y:8,value:7},{x:2,y:6,dead:true,value:4},{x:6,y:6,value:9},{x:2,y:4,value:8},{x:6,y:3,dead:false,value:6},{x:2,y:2,value:11},{x:6,y:1,value:12},{x:0,y:1,dead:true,value:5}], coins: [{x:3,y:8,value:2},{x:5,y:7,value:2},{x:3,y:6,value:3},{x:5,y:5,value:4},{x:3,y:4,value:4},{x:5,y:3,value:4},{x:3,y:2,value:4},{x:5,y:1,value:5},{x:3,y:1,value:5},{x:6,y:2,value:4}], pickups: [{x:3,y:5,type:'carrot'}] } },
  { title: 'Le ciel étoilé', theme: 'night', tutorial: 'Dernier monde : mémorise les cases sûres et fais confiance à ton instinct.', trapCount: 8, cubeCount: 9, coinCount: 10, bossHp: 160, bossFireInterval: 1500, bossDamage: 18, doubleShot: true, mechanic: 'mémoire des étoiles' },
  { title: 'Constellation carotte', theme: 'night', trapCount: 9, cubeCount: 9, coinCount: 11, bossHp: 170, bossFireInterval: 1450, bossDamage: 18, doubleShot: true, mechanic: 'constellations bonus' },
  { title: 'La lune rousse', theme: 'night', trapCount: 9, cubeCount: 10, coinCount: 11, bossHp: 180, bossFireInterval: 1400, bossDamage: 19, doubleShot: true, pattern: 'cross', mechanic: 'lune rouge' },
  { title: 'Le terrier des étoiles', theme: 'night', tutorial: 'Tu approches du grand défi. Chaque mouvement compte !', trapCount: 10, cubeCount: 10, coinCount: 12, bossHp: 190, bossFireInterval: 1350, bossDamage: 19, doubleShot: true, pattern: 'cross', mechanic: 'nuit étoilée', layout: { traps: [{x:1,y:8},{x:7,y:8},{x:1,y:7},{x:7,y:7},{x:1,y:5},{x:6,y:5},{x:1,y:4},{x:7,y:3},{x:1,y:2},{x:8,y:1}], cubes: [{x:2,y:8,value:7},{x:6,y:8,value:7},{x:2,y:6,dead:true,value:4},{x:6,y:6,value:9},{x:0,y:5,value:8},{x:6,y:4,dead:false,value:6},{x:2,y:3,value:11},{x:6,y:3,value:8},{x:0,y:2,dead:true,value:5},{x:7,y:1,value:14}], coins: [{x:3,y:8,value:2},{x:5,y:7,value:2},{x:3,y:6,value:3},{x:5,y:5,value:3},{x:3,y:4,value:4},{x:5,y:4,value:4},{x:3,y:3,value:4},{x:5,y:2,value:5},{x:3,y:2,value:5},{x:5,y:1,value:5},{x:3,y:1,value:6},{x:6,y:2,value:4}], pickups: [{x:3,y:5,type:'shield'}] } },
  { title: 'Gardien des nuages', theme: 'sky', trapCount: 9, cubeCount: 10, coinCount: 12, bossHp: 200, bossFireInterval: 1300, bossDamage: 20, doubleShot: true, special: 'wind' },
  { title: 'Orage de confettis', theme: 'sky', trapCount: 10, cubeCount: 10, coinCount: 13, bossHp: 215, bossFireInterval: 1250, bossDamage: 20, doubleShot: true, special: 'wind' },
  { title: 'Le sommet enchanté', theme: 'sky', tutorial: 'Une dernière ascension ! Gagne des pièces pour célébrer ta victoire.', trapCount: 10, cubeCount: 10, coinCount: 14, bossHp: 230, bossFireInterval: 1200, bossDamage: 21, doubleShot: true, pattern: 'cross', special: 'wind' },
  { title: 'Le grand terrier', theme: 'finale', tutorial: 'Le boss final est là. Courage, petit héros !', trapCount: 11, cubeCount: 10, coinCount: 15, bossHp: 250, bossFireInterval: 1150, bossDamage: 22, doubleShot: true, pattern: 'cross', special: 'finale', mechanic: 'épreuve finale', layout: { traps: [{x:1,y:8},{x:7,y:8},{x:1,y:7},{x:7,y:7},{x:2,y:6},{x:6,y:6},{x:1,y:4},{x:7,y:4},{x:2,y:3},{x:6,y:2},{x:2,y:1}], cubes: [{x:2,y:8,value:8},{x:6,y:8,value:8},{x:2,y:7,dead:true,value:5},{x:6,y:7,value:10},{x:0,y:5,value:9},{x:6,y:5,dead:false,value:7},{x:2,y:4,value:12},{x:6,y:3,value:10},{x:0,y:2,dead:true,value:6},{x:6,y:1,value:15}], coins: [{x:3,y:8,value:2},{x:5,y:8,value:2},{x:3,y:7,value:3},{x:5,y:6,value:3},{x:3,y:5,value:4},{x:5,y:4,value:4},{x:3,y:4,value:5},{x:5,y:3,value:5},{x:3,y:2,value:5},{x:5,y:2,value:5},{x:3,y:1,value:6},{x:5,y:1,value:6},{x:6,y:4,value:4},{x:7,y:2,value:7},{x:7,y:1,value:7}], pickups: [{x:3,y:6,type:'shield'},{x:5,y:5,type:'carrot'}] } }
];

if (typeof window !== 'undefined') window.CAMPAIGN = CAMPAIGN;
